export interface profile
{
    username?:string,
    name?:string,
    email?:string,
    dob?:Date,
    gender?:string,
    phonenumber?:string,
    aboutme?:string,
    status?:string,
    imgstr?:string,
    schoolname?:string,
    workplace?:string,
    clgname?:string,
    instalink?:string,
    twitterlink?:string,
    linkdinlink?:string,
    facebooklink?:string
}